server:
  http_listen_port: 3200
  grpc_listen_port: 4317

distributor:
  receivers:
    otlp:
      protocols:
        grpc:
        http:

ingester:
  trace_idle_period: 10s
  max_block_bytes: 1_000_000
  max_block_duration: 5m

compactor:
  compaction:
    compacted_block_retention: 1h

metrics_generator:
  registry:
    external_labels:
      source: tempo

storage:
  trace:
    backend: local
    local:
      path: /tmp/tempo/traces
